import {
  Waves, Focus, Radio, Cable, Microscope, LineChart as LineChartIcon,
  Layers, Image as ImageIcon, Grid3x3, Puzzle, LayoutDashboard, FileText,
} from 'lucide-react';

export const MODULES = [
  {
    id: 'fundamentals',
    path: '/modules/fundamentals',
    name: 'Fundamentals',
    subtitle: 'Light–Tissue Interaction',
    icon: Waves,
    section: 'Foundations',
    tag: 'M01',
    blurb: 'Beer–Lambert penetration depth for arbitrary tissue optical properties.',
  },
  {
    id: 'lens-ray-tracing',
    path: '/modules/lens-ray-tracing',
    name: 'Lens & Ray Tracing',
    subtitle: 'Designer',
    icon: Focus,
    section: 'Foundations',
    tag: 'M02',
    blurb: 'Thin-lens ray diagram with focal length and aperture control.',
  },
  {
    id: 'beam-propagation',
    path: '/modules/beam-propagation',
    name: 'Beam Propagation',
    subtitle: 'Photonic Devices',
    icon: Radio,
    section: 'Foundations',
    tag: 'M03',
    blurb: 'Gaussian beam waist evolution and imported FDTD result gallery.',
  },
  {
    id: 'fiber-optic',
    path: '/modules/fiber-optic',
    name: 'Fiber Optic Probe',
    subtitle: 'Designer',
    icon: Cable,
    section: 'Instruments',
    tag: 'M04',
    blurb: 'Numerical aperture, acceptance angle, and probe spot size.',
  },
  {
    id: 'microscope',
    path: '/modules/microscope',
    name: 'Microscope & Confocal',
    subtitle: 'Explorer',
    icon: Microscope,
    section: 'Instruments',
    tag: 'M05',
    blurb: 'Widefield vs. confocal PSF and pinhole trade-offs.',
  },
  {
    id: 'raman',
    path: '/modules/raman',
    name: 'Raman Analyzer',
    subtitle: 'Spectrum',
    icon: LineChartIcon,
    section: 'Instruments',
    tag: 'M06',
    blurb: 'Load a Raman spectrum, apply baseline correction, mark peaks.',
  },
  {
    id: 'oct',
    path: '/modules/oct',
    name: 'OCT Viewer',
    subtitle: 'B-scan',
    icon: Layers,
    section: 'Instruments',
    tag: 'M07',
    blurb: 'Optical coherence tomography B-scan and depth profile.',
  },
  {
    id: 'image-processing',
    path: '/modules/image-processing',
    name: 'Image Processing',
    subtitle: 'Dashboard',
    icon: ImageIcon,
    section: 'Processing',
    tag: 'M08',
    blurb: 'Grayscale, threshold, edge detection on biomedical images.',
  },
  {
    id: 'sim',
    path: '/modules/sim',
    name: 'SIM Demonstrator',
    subtitle: 'Structured Illumination',
    icon: Grid3x3,
    section: 'Processing',
    tag: 'M09',
    blurb: 'Before/after resolution comparison for structured illumination.',
  },
  {
    id: 'system-builder',
    path: '/modules/system-builder',
    name: 'System Builder',
    subtitle: 'Virtual Instrument',
    icon: Puzzle,
    section: 'Portfolio',
    tag: 'M10',
    blurb: 'Combine module outputs into a single virtual instrument.',
  },
  {
    id: 'results-dashboard',
    path: '/modules/results-dashboard',
    name: 'Results Dashboard',
    subtitle: 'Overview',
    icon: LayoutDashboard,
    section: 'Portfolio',
    tag: 'M11',
    blurb: 'Every result you saved from other modules, in one place.',
  },
  {
    id: 'report',
    path: '/modules/report',
    name: 'Report Generator',
    subtitle: 'Export',
    icon: FileText,
    section: 'Portfolio',
    tag: 'M12',
    blurb: 'Printable capstone report of your virtual instrument.',
  },
];

export const MODULE_MAP = Object.fromEntries(MODULES.map((m) => [m.id, m]));

export const SIDEBAR_SECTIONS = ['Foundations', 'Instruments', 'Processing', 'Portfolio'];
